version: "2.2"
services:
  app:
    build: .
    env_file: ../.env
    links:
      - mysql
    ports:
      - "5000:5000"
    environment:
      JSON_SORT_KEYS: "${JSON_SORT_KEYS}"
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DB: "${MYSQL_DB}"

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ''
    volumes:
      - /home/thiago/dev/mysql2:/var/lib/mysql
